FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

WORKDIR /app

ARG PHEYE_MODEL=pii_en_small
ENV PHEYE_MODEL=${PHEYE_MODEL}

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY models/ /app/models/
COPY download_model.py /app
RUN python3 /app/download_model.py

COPY app.py /app
COPY run.sh /app

ENV HF_HUB_DISABLE_TELEMETRY=1
ENV HF_HUB_OFFLINE=1
ENV DO_NOT_TRACK=1

CMD ["/app/run.sh"]
