services:

  pii-base:
    image: philterd/ph-eye:${PHEYE_VERSION:-1.2.5}-pii_base-gpu
    ports:
      - "8001:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  hospitals:
    image: philterd/ph-eye:${PHEYE_VERSION:-1.2.5}-hospitals-gpu
    ports:
      - "8002:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  medical-conditions:
    image: philterd/ph-eye:${PHEYE_VERSION:-1.2.5}-medical_conditions-gpu
    ports:
      - "8003:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  french-persons:
    image: philterd/ph-eye:${PHEYE_VERSION:-1.2.5}-french_persons-gpu
    ports:
      - "8004:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  french-medical:
    image: philterd/ph-eye:${PHEYE_VERSION:-1.2.5}-french_medical-gpu
    ports:
      - "8005:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
