services:

  pii-base:
    image: philterd/ph-eye:1.2.5-pii_base
    ports:
      - "8001:5000"

  hospitals:
    image: philterd/ph-eye:1.2.5-hospitals
    ports:
      - "8002:5000"

  medical-conditions:
    image: philterd/ph-eye:1.2.5-medical_conditions
    ports:
      - "8003:5000"

  french-persons:
    image: philterd/ph-eye:1.2.5-french_persons
    ports:
      - "8004:5000"

  french-medical:
    image: philterd/ph-eye:1.2.5-french_medical
    ports:
      - "8005:5000"
